### ISSUE TITLE
Add phpversion to phpstan

### ISSUE THREAD

**Issue by Sieg** [OXID-eSales/module-template#36]
This will check for functionality to fit the version range.

Example:

```
parameters:
    phpVersion:
        min: 80200
        max: 80499
```
